name: Deploy to HF Spaces

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Git
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "github-actions"

      - name: Clone Space
        run: |
          git clone https://huggingface.co/spaces/tmpai/Hiroyuki-SLM space

      - name: Sync files
        run: |
          rsync -av --delete \
            --exclude '.git' \
            --exclude '.github' \
            ./ space/

      - name: Commit & Push
        run: |
          cd space
          git add .

          COMMIT_MSG="${{ github.event.head_commit.message || 'Update from GitHub' }} (from GitHub)"

          git commit -m "$COMMIT_MSG" || echo "no changes"
          git push https://tmPAi-9910:${{ secrets.HF_TOKEN }}@huggingface.co/spaces/tmpai/Hiroyuki-SLM
